<?php
if( ! defined( 'ABSPATH' ) ) exit;
################################################################
# Animate Return Options | @since 1.0.1 | using in customizer
################################################################
if( ! class_exists( 'LanaAnimate' ) ) {
	class LanaAnimate {
		static function choices() {
			return array(
				'bounce'				=> __( 'Bounce', 'lana' ),
				'flash'					=> __( 'Flash', 'lana' ),
				'pulse'					=> __( 'Pulse', 'lana' ),
				'rubberBand'			=> __( 'Rubber Band', 'lana' ),
				'shake'					=> __( 'Shake', 'lana' ),
				'swing'					=> __( 'Swing', 'lana' ),
				'tada'					=> __( 'Tada', 'lana' ),
				'wobble'				=> __( 'Wobble', 'lana' ),
				'jello'					=> __( 'Jello', 'lana' ),
				'bounceIn'				=> __( 'Bounce In', 'lana' ),
				'bounceInDown'			=> __( 'Bounce In Down', 'lana' ),
				'bounceInLeft'			=> __( 'Bounce In Left', 'lana' ),
				'bounceInRight'			=> __( 'Bounce In Right', 'lana' ),
				'bounceInUp'			=> __( 'Bounce In Up', 'lana' ),
				'bounceOut'				=> __( 'Bounce Out', 'lana' ),
				'bounceOutDown'			=> __( 'Bounce Out Down', 'lana' ),
				'bounceOutLeft'			=> __( 'Bounce Out Left', 'lana' ),
				'bounceOutRight'		=> __( 'Bounce Out Right', 'lana' ),
				'bounceOutUp'			=> __( 'Bounce Out Up', 'lana' ),
				'fadeIn'				=> __( 'Fade In', 'lana' ),
				'fadeInDown'			=> __( 'Fade In Down', 'lana' ),
				'fadeInDownBig'			=> __( 'Fade In Down Big', 'lana' ),
				'fadeInLeft'			=> __( 'Fade In Left', 'lana' ),
				'fadeInLeftBig'			=> __( 'Fade In Left Big', 'lana' ),
				'fadeInRight'			=> __( 'Fade In Right', 'lana' ),
				'fadeInRightBig'		=> __( 'Fade In Right Big', 'lana' ),
				'fadeInUp'				=> __( 'Fade In Up', 'lana' ),
				'fadeInUpBig'			=> __( 'Fade In Up Big', 'lana' ),
				'fadeOut'				=> __( 'Fade Out', 'lana' ),
				'fadeOutDown'			=> __( 'Fade Out Down', 'lana' ),
				'fadeOutDownBig'		=> __( 'Fade Out Down Big', 'lana' ),
				'fadeOutLeft'			=> __( 'Fade Out Left', 'lana' ),
				'fadeOutLeftBig'		=> __( 'Fade Out Left Big', 'lana' ),
				'fadeOutRight'			=> __( 'Fade Out Right', 'lana' ),
				'fadeOutRightBig'		=> __( 'Fade Out Right Big', 'lana' ),
				'fadeOutUp'				=> __( 'Fade Out Up', 'lana' ),
				'fadeOutUpBig'			=> __( 'Fade Out Up Big', 'lana' ),
				'flip'					=> __( 'Flip', 'lana' ),
				'flipInX'				=> __( 'Flip In X', 'lana' ),
				'flipInY'				=> __( 'Flip In Y', 'lana' ),
				'flipOutX'				=> __( 'Flip Out X', 'lana' ),
				'flipOutY'				=> __( 'Flip Out Y', 'lana' ),
				'lightSpeedIn'			=> __( 'Light Speed In', 'lana' ),
				'lightSpeedOut'			=> __( 'Light Speed Out', 'lana' ),
				'rotateIn'				=> __( 'Rotate In', 'lana' ),
				'rotateInDownLeft'		=> __( 'Rotate In Down Left', 'lana' ),
				'rotateInDownRight'		=> __( 'Rotate In Down Right', 'lana' ),
				'rotateInUpLeft'		=> __( 'Rotate In Up Left', 'lana' ),
				'rotateInUpRight'		=> __( 'Rotate In Up Right', 'lana' ),
				'rotateOut'				=> __( 'Rotate Out', 'lana' ),
				'rotateOutDownLeft'		=> __( 'Rotate Out Down Left', 'lana' ),
				'rotateOutDownRight'	=> __( 'Rotate Out Down Right', 'lana' ),
				'rotateOutUpLeft'		=> __( 'Rotate Out Up Left', 'lana' ),
				'rotateOutUpRight'		=> __( 'Rotate Out Up Right', 'lana' ),
				'slideInUp'				=> __( 'Slide In Up', 'lana' ),
				'slideInDown'			=> __( 'Slide In Down', 'lana' ),
				'slideInLeft'			=> __( 'Slide In Left', 'lana' ),
				'slideInRight'			=> __( 'Slide In Right', 'lana' ),
				'slideOutUp'			=> __( 'Slide Out Up', 'lana' ),
				'slideOutDown'			=> __( 'Slide Out Down', 'lana' ),
				'slideOutLeft'			=> __( 'Slide Out Left', 'lana' ),
				'slideOutRight'			=> __( 'Slide Out Right', 'lana' ),
				'zoomIn'				=> __( 'Zoom In', 'lana' ),
				'zoomInDown'			=> __( 'Zoom In Down', 'lana' ),
				'zoomInLeft'			=> __( 'Zoom In Left', 'lana' ),
				'zoomInRight'			=> __( 'Zoom In Right', 'lana' ),
				'zoomInUp'				=> __( 'Zoom In Up', 'lana' ),
				'zoomOut'				=> __( 'Zoom Out', 'lana' ),
				'zoomOutDown'			=> __( 'Zoom Out Down', 'lana' ),
				'zoomOutLeft'			=> __( 'Zoom Out Left', 'lana' ),
				'zoomOutRight'			=> __( 'Zoom Out Right', 'lana' ),
				'zoomOutUp'				=> __( 'Zoom Out Up', 'lana' ),
				'hinge'					=> __( 'Hinge', 'lana' ),
				'rollIn'				=> __( 'Roll In', 'lana' ),
				'rollOut'				=> __( 'Roll Out', 'lana' ) 
			); 
		}
	}
}